# Generated by Django 4.0.4 on 2022-06-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0003_blog_blog_pic'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='Blog',
        ),
    ]
