# Generated by Django 4.0.4 on 2022-06-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0004_alter_blog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
